name: NodeJS with Gulp

on:
  push:
    branches: [ "package-*" ]
  pull_request:
    branches: [ "package-*" ]

jobs:
#  linux:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [20.x]
#
#    steps:
#    - uses: actions/checkout@v4
#
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v4
#      with:
#        node-version: ${{ matrix.node-version }}
#
#    - name: Install dependencies
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libkrb5-dev
#
#    - name: Build
#      run: |
#        npm install
#        npm run gulp vscode-linux-x64
#        cp -r ../VSCode-linux-x64 .
#        mv VSCode-linux-x64 code-x17-linux-x64
#        zip -r code-x17-linux-x64.zip code-x17-linux-x64
#
#    - name: Upload artifact
#      uses: actions/upload-artifact@v3
#      with:
#        name: code-x17-linux-x64
#        path: code-x17-linux-x64.zip

  windows:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

#    - name: Install dependencies
#      run: |
#        sudo apt-get update
#        sudo apt-get install -y libkrb5-dev

    - name: Build
      run: |
        cd "C:/Program Files (x86)/Windows Kits/10/bin"
        dir -s signtool.exe
